//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public System.Guid CustomerID { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Notes { get; set; }
    }
}
